project_id = "lyeyzdbplrgqsvyxpfek"

[functions.get-reviews]
verify_jwt = false

[functions.list-calendar-events]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false

[functions.update-calendar-event]
verify_jwt = false

[functions.delete-calendar-event]
verify_jwt = false
