export { default as SettingsSection } from "./SettingsSection";
export { default as AgendaSection } from "./AgendaSection";
export { default as CajaSection } from "./CajaSection";
export { default as ClientsSection } from "./ClientsSection";
export { default as CatalogSection } from "./CatalogSection";
export { default as EquipoSection } from "./EquipoSection";
export { default as ReportsSection } from "./ReportsSection";
export { default as InicioSection } from "./InicioSection";
export { default as NegocioSection } from "./NegocioSection";
