// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-tenants.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.75.0";
import { z } from "npm:zod@^3.25.76";
var search_tenants_default = defineTool({
  name: "search_tenants",
  title: "Search salons",
  description: "Search publicly listed salons on Glowapp. Optionally filter by city (case-insensitive substring). Returns basic public info: name, slug, city, tagline.",
  inputSchema: {
    city: z.string().optional().describe("Optional city filter (case-insensitive substring match)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results to return. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    const supabase = createClient(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.rpc("get_public_tenants");
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    let rows = data ?? [];
    if (city) {
      const needle = city.toLowerCase();
      rows = rows.filter((r) => (r.city ?? "").toLowerCase().includes(needle));
    }
    rows = rows.slice(0, limit ?? 20);
    const summary = rows.map((r) => `- ${r.name} (/${r.slug})${r.city ? ` \u2014 ${r.city}` : ""}${r.tagline ? `: ${r.tagline}` : ""}`).join("\n");
    return {
      content: [
        {
          type: "text",
          text: rows.length ? `Found ${rows.length} salon(s):
${summary}` : "No salons found."
        }
      ],
      structuredContent: { count: rows.length, tenants: rows }
    };
  }
});

// src/lib/mcp/tools/get-tenant.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.75.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_tenant_default = defineTool2({
  name: "get_tenant",
  title: "Get salon details",
  description: "Get public details of a salon by its slug (e.g. 'cristina-munoz'). Returns name, city, address, phone, description, tagline, and social links.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Salon slug, e.g. 'cristina-munoz'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    const supabase = createClient2(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.rpc("get_public_tenant_by_slug", { _slug: slug });
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const tenant = Array.isArray(data) ? data[0] : data;
    if (!tenant) {
      return { content: [{ type: "text", text: `Salon '${slug}' not found or not active.` }], isError: true };
    }
    return {
      content: [
        {
          type: "text",
          text: `${tenant.name} \u2014 ${tenant.city ?? ""}
${tenant.tagline ?? ""}
${tenant.description ?? ""}
Phone: ${tenant.phone ?? "n/a"}
Address: ${tenant.address ?? "n/a"}
Instagram: ${tenant.instagram_url ?? "n/a"}
Book: https://glowapp.app/${tenant.slug}`
        }
      ],
      structuredContent: { tenant }
    };
  }
});

// src/lib/mcp/tools/get-tenant-reviews.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.75.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_tenant_reviews_default = defineTool3({
  name: "get_tenant_reviews",
  title: "Get salon reviews",
  description: "Get recent approved reviews for a salon by its slug.",
  inputSchema: {
    slug: z3.string().trim().min(1).describe("Salon slug."),
    limit: z3.number().int().min(1).max(20).optional().describe("Max reviews. Default 6.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, limit }) => {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_ANON_KEY ?? process.env.SUPABASE_PUBLISHABLE_KEY;
    const supabase = createClient3(url, key, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data: tenantRows, error: tErr } = await supabase.rpc("get_public_tenant_by_slug", { _slug: slug });
    if (tErr) return { content: [{ type: "text", text: `Error: ${tErr.message}` }], isError: true };
    const tenant = Array.isArray(tenantRows) ? tenantRows[0] : tenantRows;
    if (!tenant) return { content: [{ type: "text", text: `Salon '${slug}' not found.` }], isError: true };
    const { data, error } = await supabase.rpc("get_tenant_reviews", {
      p_tenant_id: tenant.id,
      p_limit: limit ?? 6
    });
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const rows = data ?? [];
    const summary = rows.map((r) => `\u2605${r.rating} \u2014 ${r.reviewer_name}: ${r.comment ?? ""}`).join("\n");
    return {
      content: [{ type: "text", text: rows.length ? summary : "No reviews yet." }],
      structuredContent: { count: rows.length, reviews: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "glowapp-mcp",
  title: "Glowapp",
  version: "0.1.0",
  instructions: "Public read-only tools for Glowapp \u2014 the social booking platform for beauty & wellness salons in Spain. Use `search_tenants` to discover salons (optionally by city), `get_tenant` to fetch a salon's public details by slug, and `get_tenant_reviews` to read recent reviews.",
  tools: [search_tenants_default, get_tenant_default, get_tenant_reviews_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
